server:
  port: 8080
  #  url : http://10.50.34.123:8080
  url: http://10.50.34.123:8080
  resource-path: "src/main/resources/static/uploads/"
spring:
  datasource:
    # you must change url to docker database container name
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3303/yun
    username: 'COMPOSE_USER'
    password: 'COMPOSE_PASSWORD'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create # ????? none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
springdoc:
  packages-to-scan: com.example.team4_be
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

